apiVersion: v1
kind: Service
metadata:
  name: game-server
spec:
  ports:
    - name: https
      port: 80
      targetPort: 9443
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: game-server
  labels:
    kubernetes.io/service-name: game-server
    endpointslice.kubernetes.io/managed-by: cluster-admins
addressType: IPv4
endpoints:
  - addresses:
      - ${SECRET_GAME_SERVER_ADDR}
    conditions:
      ready: true
ports:
  - name: https
    port: 9443
---