apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8123
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: home-assistant
  labels:
    kubernetes.io/service-name: home-assistant
    endpointslice.kubernetes.io/managed-by: cluster-admins
addressType: IPv4
endpoints:
  - addresses:
      - ${SECRET_HASS_ADDR}
    # https://github.com/argoproj/argo-cd/issues/15554
    conditions:
      ready: true
ports:
  - name: http
    port: 8123
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: hass
# spec:
#   type: ExternalName
#   ports:
#     - name: http
#       port: 8123
#   externalName: ${SECRET_HASS_ADDR}