apiVersion: v1
kind: Service
metadata:
  name: nc
spec:
  ports:
    - name: http
      port: 80
      targetPort: 11000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: nc
  labels:
    kubernetes.io/service-name: nc
    endpointslice.kubernetes.io/managed-by: cluster-admins
addressType: IPv4
endpoints:
  - addresses:
      - ${SECRET_NC_ADDR}
    conditions:
      ready: true
ports:
  - name: http
    port: 11000
---