apiVersion: v1
kind: Service
metadata:
  name: opn
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: opn
  labels:
    kubernetes.io/service-name: opn
    endpointslice.kubernetes.io/managed-by: cluster-admins
addressType: IPv4
endpoints:
  - addresses:
      - ${SECRET_OPN_ADDR}
    conditions:
      ready: true
ports:
  - name: http
    port: 80
---