apiVersion: v1
kind: Service
metadata:
  name: pmox1
spec:
  ports:
    - name: https
      port: 80
      targetPort: 8123
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: pmox1
  labels:
    kubernetes.io/service-name: pmox1
    endpointslice.kubernetes.io/managed-by: cluster-admins
addressType: IPv4
endpoints:
  - addresses:
      - ${SECRET_PMX1_ADDR}
    conditions:
      ready: true
ports:
  - name: https
    port: 8006