apiVersion: v1
kind: Service
metadata:
  name: ptero
spec:
  ports:
    - name: https
      port: 80
      targetPort: 443
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ptero
  labels:
    kubernetes.io/service-name: ptero
    endpointslice.kubernetes.io/managed-by: cluster-admins
addressType: IPv4
endpoints:
  - addresses:
      - ${SECRET_PTERO_ADDR}
    conditions:
      ready: true
ports:
  - name: https
    port: 443
---