apiVersion: v1
kind: Service
metadata:
  name: ptero-node1
spec:
  ports:
    - name: https
      port: 80
      targetPort: 8080
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ptero-node1
  labels:
    kubernetes.io/service-name: ptero-node1
    endpointslice.kubernetes.io/managed-by: cluster-admins
addressType: IPv4
endpoints:
  - addresses:
      - ${SECRET_PTERO_NODE1_ADDR}
    conditions:
      ready: true
ports:
  - name: https
    port: 8080
---