apiVersion: v1
kind: Service
metadata:
  name: vw
spec:
  ports:
    - name: http
      port: 443
      targetPort: 8000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: vw
  labels:
    kubernetes.io/service-name: vw
    endpointslice.kubernetes.io/managed-by: cluster-admins
addressType: IPv4
endpoints:
  - addresses:
      - ${SECRET_VW_ADDR}
    conditions:
      ready: true
ports:
  - name: http
    port: 8000
---
