apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: app-template
  namespace: flux-system
spec:
  chart: app-template
  interval: 5m0s
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: bjw-s
  version: 3.6.1
