---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  nfs:
    server: ${SECRET_NFS_ADDR}
    path: "/kubernetes/PostgresBackups/"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-nfs