apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-private-default
      namespace: network
      sectionName: https-wildcard-secret-private-domain
  hostnames:
    - "grafana.${SECRET_PRIVATE_DOMAIN}"
  rules:
    - backendRefs:
        - name: kube-prometheus-stack-grafana
          port: 80
