apiVersion: v1
kind: Secret
metadata:
    name: infisical-auth-secrets
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:nLnuLHAmv8usLsQwaOs8BCRhvAlEDmIIFRdJQb0hWvp4mR9WoH5GDhdgOds=,iv:wC8q56HFjBHODm1oxUzKb01JNdwc+sgBoY4oR7QQUak=,tag:ej8pq7ViEeDY7FAkjaFUDg==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:7SQEtk4YnoWEPqb4wMHKCZKqzZ8CLs0R56/R8uCxUMc=,iv:/Gt291vb0XoLCexLNSMVqwVzSEIJ8GshBcU/6feCHaw=,tag:huj993PAo25yZXIx7Fw0eA==,type:str]
    SITE_URL: ENC[AES256_GCM,data:PyZ7hGJvIUZouocozyhoZJ/Jar+wVsTePIJqVcpey0e6lQ==,iv:NRvLwvYCCVk5b2030emvUMtN+UFhmV+xYZ/Vh4bM+/k=,tag:z1BM3DloFc4U0wAR8hFPXw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:u0sqBPm6Afy7eZrhs5/Uy27x+ov1IowmB6rbmd9JfT9aSN163Sm/SYvIc4Py+oODLC0hU2g/,iv:yFYr65gxolMKh4OMShOpJjmgXBnbcyc7CJcsfu3tcsE=,tag:2BPd7X0bqUD/xEnSyHEpQg==,type:str]
sops:
    age:
        - recipient: age15uem8zcylkmwcsgxulla00cn0yrgvhusua0mg5emuav4ja30cvvq3sdu0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbmhzbEJabk5SL211NlBm
            OFd6RmJHK3pvVU0zUTdwMTlORHpuYlI2QVgwCmhTQXhtRDlxcngrclFtM2liVVg2
            ektkcTMyWU5MU3RrMk5WQk1HcWtGSEUKLS0tIDAxU21lMS8wRnJKNlcyRE8xM1Nh
            MW1NUGYxVlJISEJkMDByODFUbHlZZmcKb3f8bhgsHXyE4kaSuZEBvUbaGtAz6SQy
            bE0FUEWymYBD50yhBjgnbZuOrVqBp+J1aXOkE25PkKwtZPQx0NGs/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T18:53:27Z"
    mac: ENC[AES256_GCM,data:VkZK8GcVpGdqqvln+eCebUo1Duqc5JOFLImdgkw/B7qxL1eWYQI0tyrn5kcReaoBtk3GUSx9CfUIqHRAwrv6xm3AuypkUy0eQDUqUYDX3gr9lSfvr+ORLir+RenCEWtkPzu5LWarlIAV8d57wFNWJA78Qj9SUq2PGsEW7FikVUs=,iv:7FurH0dbqyvWGoTWxnjuyN2PqFDd8TWKPQdlhhEwrG0=,tag:t8tZrX5+zZyvkeBcDUKvGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
