apiVersion: v1
kind: Secret
metadata:
    name: infisical-auth-secrets
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:nLnuLHAmv8usLsQwaOs8BCRhvAlEDmIIFRdJQb0hWvp4mR9WoH5GDhdgOds=,iv:wC8q56HFjBHODm1oxUzKb01JNdwc+sgBoY4oR7QQUak=,tag:ej8pq7ViEeDY7FAkjaFUDg==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:7SQEtk4YnoWEPqb4wMHKCZKqzZ8CLs0R56/R8uCxUMc=,iv:/Gt291vb0XoLCexLNSMVqwVzSEIJ8GshBcU/6feCHaw=,tag:huj993PAo25yZXIx7Fw0eA==,type:str]
    SITE_URL: ENC[AES256_GCM,data:PyZ7hGJvIUZouocozyhoZJ/Jar+wVsTePIJqVcpey0e6lQ==,iv:NRvLwvYCCVk5b2030emvUMtN+UFhmV+xYZ/Vh4bM+/k=,tag:z1BM3DloFc4U0wAR8hFPXw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:rUSI7moOhv+jFsQ+GQZdfQxWKSjVappFm7/tXt3xrrf8LgAl,iv:AoW7teB/JAL4a23L29VgJS6+3bMXW32SJ/04KdiCvrQ=,tag:YaqCQYRXNqzZYE17dDXrhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbmhzbEJabk5SL211NlBm
            OFd6RmJHK3pvVU0zUTdwMTlORHpuYlI2QVgwCmhTQXhtRDlxcngrclFtM2liVVg2
            ektkcTMyWU5MU3RrMk5WQk1HcWtGSEUKLS0tIDAxU21lMS8wRnJKNlcyRE8xM1Nh
            MW1NUGYxVlJISEJkMDByODFUbHlZZmcKb3f8bhgsHXyE4kaSuZEBvUbaGtAz6SQy
            bE0FUEWymYBD50yhBjgnbZuOrVqBp+J1aXOkE25PkKwtZPQx0NGs/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15uem8zcylkmwcsgxulla00cn0yrgvhusua0mg5emuav4ja30cvvq3sdu0r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T12:28:33Z"
    mac: ENC[AES256_GCM,data:qOe6RiOPty/mrci5oacVNSm9fNGa/iM8PjR72WlVbWQqWD9PTvopZ9TeR6/dBuCaq/RwCMEb7UcCJZzSwfDpBe2Z9m4z+gsgk/KmSBWemrkmnlL1mBa6Ck4V+d1EqUMC8x9+abkdEMN47rDnco4jT1pcZbqooR1ps+H5LgFUauY=,iv:6MHGC9Tr81SgxyG6A0p5p4UumkvnaziDwuAfKgXcNsc=,tag:GFTxRkkict1PPaqYs1GFtQ==,type:str]
    version: 3.13.1
