---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name infisical-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      type: Opaque
      data:
        dbUri: '{{ index . "uri" }}'
  dataFrom:
  - extract:
      key: postgres-pguser-infisical