# # -- Overrides the default release name
# nameOverride: ""
# # -- Overrides the full name of the release, affecting resource names
# fullnameOverride: ""

infisical:
  enabled: true # -- Enable Infisical chart deployment
  name: infisical # -- Sets the name of the deployment within this chart

  # -- Automatically migrates new database schema when deploying
  autoDatabaseSchemaMigration: true

  databaseSchemaMigrationJob:
    image:
      repository: ghcr.io/groundnuty/k8s-wait-for
      tag: no-root-v2.0
      pullPolicy: IfNotPresent

  serviceAccount:
    # -- Creates a new service account if true, with necessary permissions for this chart. If false and `serviceAccount.name` is not defined, the chart will attempt to use the Default service account
    create: true
    annotations: {}
    name: null

  fullnameOverride: ""
  podAnnotations: {}
  deploymentAnnotations: {}
  replicaCount: 1

  image:
    repository: infisical/infisical
    tag: "v0.132.4-postgres"
    pullPolicy: IfNotPresent
    imagePullSecrets: []

  affinity: {}
  # -- Kubernetes Secret reference containing Infisical root credentials
  kubeSecretRef: "infisical-auth-secrets"

  service:
    annotations: {}
    type: ClusterIP

  resources:
    limits:
      memory: 600Mi
    requests:
      cpu: 350m

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  ingressClassName: traefik-private
  nginx:
    enabled: false
  hostName: &infisical-host infisical.${SECRET_PRIVATE_DOMAIN}
  tls:
    - secretName: ${SECRET_PRIVATE_DOMAIN//./-}-tls
      hosts:
        - *infisical-host

postgresql:
  # # -- Enables an in-cluster PostgreSQL deployment. To achieve HA for Postgres, we recommend deploying https://github.com/zalando/postgres-operator instead.
  enabled: false
  # # -- PostgreSQL resource name
  # name: "postgresql"
  # # -- Full name override for PostgreSQL resources
  # fullnameOverride: "postgresql"

  # auth:
  #   # -- Database username for PostgreSQL
  #   username: infisical
  #   # -- Password for PostgreSQL database access
  #   password: root
  #   # -- Database name for Infisical
  #   database: infisicalDB

  useExistingPostgresSecret:
    # -- Set to true if using an existing Kubernetes secret that contains PostgreSQL connection string
    enabled: true
    existingConnectionStringSecret:
      # -- Kubernetes secret name containing the PostgreSQL connection string
      name: "infisical-db-secret"
      # -- Key name in the Kubernetes secret that holds the connection string
      key: "dbUri"



redis:
  # -- Enables an in-cluster Redis deployment
  enabled: true
  # -- Redis resource name
  name: "redis"
  # -- Full name override for Redis resources
  fullnameOverride: "redis"

  cluster:
    # -- Clustered Redis deployment
    enabled: false
  
  # -- Requires a password for Redis authentication
  usePassword: true

  auth:
    # -- Redis password
    password: "mysecretpassword"

  # -- Redis deployment type (e.g., standalone or cluster)
  architecture: standalone