---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name actual
spec:
  dependsOn:
    - name: longhorn
      namespace: storage
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  releaseName: *name
  maxHistory: 1
  values:
    controllers:
      app:
        enabled: true
        type: deployment
        replicas: 1

        containers:
          app:
            image:
              repository: ghcr.io/actualbudget/actual-server
              tag: 25.1.0
            env:
              ACTUAL_PORT: &port 5006
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 5
                  timeoutSeconds: 20
                  periodSeconds: 30
                  failureThreshold: 5
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M

    service:
      actual:
        controller: app
        ports:
          http:
            port: *port

    ingress:
      actual:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        className: traefik-private
        hosts:
          - host: &actual-path actual.${SECRET_PRIVATE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: actual
                  port: http
        tls:
          - secretName: ${SECRET_PRIVATE_DOMAIN//./-}-tls
            hosts:
              - *actual-path

    persistence:
      actual-data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: actual-data
        globalMounts:
          - path: /data
            readOnly: false
