apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: bjw-s
  namespace: flux-system
spec:
  interval: 24h
  chart: app-template
  version: 3.5.1
  sourceRef:
    kind: HelmRepository
    name: bjw-s
    namespace: flux-system
