# flux HelmRepository for installing nginx ingress controller
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  type: oci
  interval: 15m
  url: oci://ghcr.io/actions/actions-runner-controller-charts/
