---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: nextcloud
    creationPolicy: 'Orphan'
  data:
  - secretKey: postgresql_pass
    remoteRef:
      key: postgres-pguser-nextcloud
      property: password
    sourceRef:
      storeRef:
        name: crunchy-pgo-secrets
        kind: ClusterSecretStore

  - secretKey: admin_user
    remoteRef:
      key: NC_ADMIN_USER

  - secretKey: admin_password
    remoteRef:
      key: NC_ADMIN_PASS
