image:
  repository: ghcr.io/eivarin/nextcloud
  tag: 31.0.8-fpm-alpine
nginx:
  enabled: true
  # resources:
  #   requests:
  #     cpu: 500m
  #     memory: 500Mi
  #   limits:
  #     memory: 8Gi
replicaCount: 1
env:
  TZ: ${TIMEZONE}
  # PHP_MEMORY_LIMIT: 256M

# podSecurityContext:

#   supplementalGroups:
#     - 100

affinity: &affinity
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: node-priority
              operator: In
              values:
              - "1"
      - weight: 2
        preference:
          matchExpressions:
            - key: node-priority
              operator: In
              values:
              - "2"


persistence:
  existingClaim: nextcloud
  enabled: true
  # accessMode: ReadWriteMany
  # storageClass: longhorn
  # nextcloudData:
  #   accessMode: ReadWriteMany
    # enabled: false
    # existingClaim: nextcloud
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    memory: 4Gi
hpa:
  enabled: false

ingress:
  enabled: false
service:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"

nextcloud:
  host: nc.${SECRET_PUBLIC_DOMAIN1}

  existingSecret:
    enabled: true
    secretName: nextcloud
    usernameKey: admin_user
    passwordKey: admin_password


  extraVolumes:
    - name: nfs
      nfs:
        server: "${SECRET_NFS_ADDR}"
        path: "/all"
        readOnly: false
  extraVolumeMounts:
    - name: nfs
      mountPath: "/mnt/nfs"

  configs:
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' => array(
          '127.0.0.1',         // Loopback address (localhost)
          '10.0.0.0/8',        // RFC1918 - Class A private network range
          '172.16.0.0/12',     // RFC1918 - Class B private network range
          '192.168.0.0/16',    // RFC1918 - Class C private network range
        ),
        'trusted_domains' =>
        array(
            0 => 'nc.${SECRET_PUBLIC_DOMAIN1}',
            1 => 'nc.${SECRET_PRIVATE_DOMAIN}',
            2 => 'localhost',
        ),
        'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
      );
internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: postgres-primary.databases.svc:5432
  database: nextcloud
  user: nextcloud
  # password: set by valuesFrom

externalRedis:
  enabled: true

  ## Redis host
  host: "dragonfly.databases.svc.cluster.local"

  ## Redis port
  port: "6379"


cronjob:
  enabled: true
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  curlInsecure:
  resources:
    requests:
      cpu: 5m
      memory: 10Mi
    limits:
      memory: 1Gi

postgresql:
  enabled: false

redis:
  enabled: false
  affinity: *affinity
  architecture: standalone
  auth:
    enabled: false

startupProbe:
  enabled: false
  # initialDelaySeconds: 60
  # periodSeconds: 30
  # timeoutSeconds: 10
  # failureThreshold: 10
  # successThreshold: 1
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

