
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gha-runner-scale-set-controller
  namespace: flux-system
spec:
  targetNamespace: actions-runner-system
  interval: 10m0s
  retryInterval: 1m
  path: ./kubernetes/apps/actions-runner-system/controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes