apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkwarden
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 10m0s
  retryInterval: 1m
  path: ./kubernetes/apps/default/linkwarden/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: crunchy-postgres-operator-cluster
    - name: infisical