apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name calibre
  namespace: flux-system
spec:
  targetNamespace: entertainment
  interval: 10m0s
  retryInterval: 1m
  path: ./kubernetes/apps/entertainment/calibre/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: longhorn
  postBuild:
    substitute:
      app: *name
      http_port: "8080"
      ws_port: "8081"
      http_host: "calibre.${SECRET_PRIVATE_DOMAIN}"
      ws_host: "calibre-web.${SECRET_PRIVATE_DOMAIN}"
