---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reflector
  namespace: flux-system
spec:
  targetNamespace: kube-system
  interval: 10m
  path: ./kubernetes/apps/kube-system/reflector/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
