apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
  namespace: flux-system
spec:
  targetNamespace: storage
  interval: 10m0s
  retryInterval: 1m
  path: ./kubernetes/apps/storage/openebs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes

