---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: userinit-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: crunchy-userinit-controller
      version: 0.0.4
      sourceRef:
        kind: HelmRepository
        name: crunchy-userinit
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: crunchy-postgres-operator
      namespace: databases
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: userinit-controller-helm-values