---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name kitchenowl-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: *name

  dataFrom:
    - find:
        name:
          regexp: &prefix "KITCHENOWL_(.*)"
      rewrite:
        - regexp:
            source: *prefix
            target: "$1"
