---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yml
configMapGenerator:
  - name: cilium-helm-values
    files:
      - values.yml=./helm-values.yml
configurations:
  - kustomizeconfig.yml
