controllers:
  app:
    enabled: true
    type: deployment
    replicas: 1
    pod:
      hostname: &app flaresolverr
      annotations:
        app.kubernetes.io/name: *app
        app.kubernetes.io/instance: *app
    containers:
      app:
        image:
          repository: ghcr.io/flaresolverr/flaresolverr
          tag: v3.3.21
          pullPolicy: IfNotPresent
        env:
          LOG_LEVEL: info
          LOG_HTML: false
          CAPTCHA_SOLVER: none
          TZ: ${TIMEZONE}
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            memory: 500Mi

        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: &port 8191
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probe


defaultPodOptions:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: node-priority
                operator: Gt
                value: 0
        - weight: 2
          preference:
            matchExpressions:
              - key: node-priority
                operator: Gt
                value: 1

service:
  web:
    controller: app
    ports:
      http:
        port: *port



