apiVersion: v1
kind: PersistentVolume
metadata:
  name: &name ${KS_NAME}-games
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: ${SECRET_NFS_ADDR}
    path: /Games/
