apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard
spec:
  parentRefs:
    - name: traefik-private-default
      port: 443
  hostnames:
    - "adguard.${SECRET_PRIVATE_DOMAIN}"
  rules:
    - backendRefs:
        - name: adguard
          port: 80