apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik-private
  rules:
  - host: &host hass.${SECRET_PRIVATE_DOMAIN}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: hass
            port:
              number: 8123
  tls:
    - hosts:
        - *host
      secretName: ${SECRET_PRIVATE_DOMAIN//./-}-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass-public
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/target: ${SECRET_PUBLIC_DOMAIN1}
spec:
  ingressClassName: traefik-public
  rules:
  - host: &host hass.${SECRET_PUBLIC_DOMAIN1}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: hass
            port:
              number: 8123
  tls:
    - hosts:
        - *host
      secretName: hass-${SECRET_PUBLIC_DOMAIN1//./-}-tls
