apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nc
spec:
  parentRefs:
    - name: traefik-private-default
      port: 443
    - name: traefik-public-default
      port: 443
  hostnames:
    - "nc.${SECRET_PRIVATE_DOMAIN}"
    - "nc.${SECRET_PUBLIC_DOMAIN1}"
  rules:
    - backendRefs:
        - name: nc
          port: 80