apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: omada
spec:
  parentRefs:
    - name: traefik-private-default
      port: 443
  hostnames:
    - "omada.${SECRET_PRIVATE_DOMAIN}"
  rules:
    - backendRefs:
        - name: omada
          port: 80