apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: omv
spec:
  parentRefs:
    - name: traefik-private-default
      port: 443
  hostnames:
    - "omv.${SECRET_PRIVATE_DOMAIN}"
  rules:
    - backendRefs:
        - name: omv
          port: 80