apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: opn
spec:
  parentRefs:
    - name: traefik-private-default
      port: 443
  hostnames:
    - "opn.${SECRET_PRIVATE_DOMAIN}"
  rules:
    - backendRefs:
        - name: opn
          port: 80