apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pmox
spec:
  parentRefs:
    - name: traefik-private-default
      port: 443
  hostnames:
    - "pmox.${SECRET_PRIVATE_DOMAIN}"
  rules:
    - backendRefs:
        - name: pmox
          port: 80
---