apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ptero-node1
spec:
  parentRefs:
    - name: traefik-private-default
      port: 443
  hostnames:
    - "ptero-node1.${SECRET_PRIVATE_DOMAIN}"
  rules:
    - backendRefs:
        - name: ptero-node1
          port: 80
---