apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ptero-node1
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik-private
  rules:
  - host: &host ptero-node1.${SECRET_PRIVATE_DOMAIN}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ptero-node1
            port:
              number: ${SECRET_PTERO_NODE1_PORT}
  tls:
    - hosts:
        - *host
      secretName: ${SECRET_PRIVATE_DOMAIN//./-}-tls