apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ptero
spec:
  parentRefs:
    - name: traefik-private-default
      port: 443
  hostnames:
    - "ptero.${SECRET_PRIVATE_DOMAIN}"
  rules:
    - backendRefs:
        - name: ptero
          port: 80
---