apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vw
spec:
  parentRefs:
    - name: traefik-private-default
      port: 443
    - name: traefik-public-default
      port: 443
  hostnames:
    - "vw.${SECRET_PRIVATE_DOMAIN}"
    - "vw.${SECRET_PUBLIC_DOMAIN1}"
  rules:
    - backendRefs:
        - name: vw
          port: 443
---
