apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vw
  annotations: 
    kubernetes.io/ingress.class: traefik-private
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`vw.${SECRET_PRIVATE_DOMAIN}`)
    kind: Rule
    services:
    - name: vw
      scheme: http
      port: ${SECRET_VW_PORT}
  tls:
    secretName: ${SECRET_PRIVATE_DOMAIN/./-}-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vw-public
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/target: ${SECRET_PUBLIC_DOMAIN1}
spec:
  ingressClassName: traefik-public
  rules:
  - host: &host vw.${SECRET_PUBLIC_DOMAIN1}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: vw
            port:
              number: ${SECRET_VW_PORT}
  tls:
    - hosts:
        - *host
      secretName: vw-${SECRET_PUBLIC_DOMAIN1/./-}-tls
