apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: cloudflare-api-token-secret

  data:
    - secretKey: api-token
      remoteRef:
        key: CF_TOKEN