---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-12h
spec:
  name: backup-job
  cron: "0 */12 * * *"
  task: "backup"
  groups:
  - default
  retain: 14
  concurrency: 1