---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr:
    base_url: http://sonarr:8989
    api_key: !env_var SONARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    include:
      # quality definition
      - template: sonarr-quality-definition-series
      # quality profiles Series 1080
      - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p
      # quality profiles Series 2160
      - template: sonarr-v4-quality-profile-web-2160p-alternative
      - template: sonarr-v4-custom-formats-web-2160p
      # quality profiles Anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime

    custom_formats:
      - trash_ids:
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
          - c9eafd50846d299b862ca9bb6ea91950 # x265
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10
          - name: WEB-1080p
            score: 10
      - trash_ids:
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
        assign_scores_to:
          - name: WEB-2160p
            score: 10
      - trash_ids:
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 100
          - name: WEB-1080p
            score: 100
        

radarr:
  radarr:
    base_url: http://radarr:7878
    api_key: !env_var RADARR_API_KEY
  
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
  
    include:
      # quality definition
      - template: radarr-quality-definition-movie
      # quality profiles Movies 1080
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web
      # quality profiles Movies 2160
      - template: radarr-quality-profile-uhd-bluray-web
      - template: radarr-custom-formats-uhd-bluray-web
      # quality profiles Anime
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime

    custom_formats:
      - trash_ids:
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
          - c9eafd50846d299b862ca9bb6ea91950 # x265
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10
          - name: HD Bluray + WEB
            score: 10
      - trash_ids:
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
        assign_scores_to:
          - name: UHD Bluray + WEB
            score: 10
      - trash_ids:
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 100
          - name: HD Bluray + WEB
            score: 100