---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name immich-secrets
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: *name

  data:
    - secretKey: DB_URL
      remoteRef:
        key: postgres-pguser-immich
        property: uri
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore

  dataFrom:
    - find:
        name:
          regexp: &prefix "IMMICH_(.*)"
      rewrite:
        - regexp:
            source: *prefix
            target: "$1"
