---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "webhooks-${SECRET_PUBLIC_DOMAIN1//./-}-production"
spec:
  secretName: "webhooks-${SECRET_PUBLIC_DOMAIN1//./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "webhooks.${SECRET_PUBLIC_DOMAIN1}"
  dnsNames:
  - "webhooks.${SECRET_PUBLIC_DOMAIN1}"
  - "*.webhooks.${SECRET_PUBLIC_DOMAIN1}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      # reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      # reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "traefik" # Control auto-reflection namespaces