---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name recyclarr
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"

  data:
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: RADARR_API_KEY
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: SONARR_API_KEY