apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-secret-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: pgadmin-secret-password

  data:
    - secretKey: password
      remoteRef:
        key: PGADMIN_PASSWORD