apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name bookshelf
  namespace: flux-system
spec:
  targetNamespace: entertainment
  interval: 10m0s
  retryInterval: 1m
  path: ./kubernetes/apps/entertainment/bookshelf/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: longhorn
  postBuild:
    substitute:
      app: *name
      port: "8787"
      http_host_1: "bookshelf.${SECRET_PRIVATE_DOMAIN}"
      http_host_2: "readarr.${SECRET_PRIVATE_DOMAIN}"
