apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infisical
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  interval: 10m0s
  retryInterval: 1m
  path: ./kubernetes/apps/external-secrets/infisical/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: crunchy-postgres-operator-cluster

