apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: entertainment-postgresql
  namespace: flux-system
spec:
  targetNamespace: entertainment
  interval: 10m0s
  retryInterval: 1m
  path: ./kubernetes/apps/entertainment/DBs/postgresql
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes

