controllers:
  app:
    enabled: true
    type: deployment
    replicas: 1
    pod:
      hostname: &name jellyfin
      annotations:
        app.kubernetes.io/name: *name
        app.kubernetes.io/instance: *name
    containers:
      app:
        image:
          repository: jellyfin/jellyfin
          tag: 10.10.5
          pullPolicy: IfNotPresent
        env:
          PUID: 1000
          PGID: 1000
          TZ: ${TIMEZONE}
        resources:
          requests:
            gpu.intel.com/i915: "1"
            memory: 1Gi
          limits:
            gpu.intel.com/i915: "1"
            memory: 4Gi

        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: &port 8096
              initialDelaySeconds: 20
              periodSeconds: 30
              timeoutSeconds: 20
              failureThreshold: 5
          readiness: *probe

defaultPodOptions:
  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: 'true'

service:
  web:
    controller: app
    ports:
      http:
        port: *port

route:
  main:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: traefik-private-default
        namespace: network
        sectionName: https-wildcard-secret-private-domain
      - name: traefik-public-default
        namespace: network
        sectionName: https-jellyfin
    hostnames:
      - "jellyfin.${SECRET_PRIVATE_DOMAIN}"
      - "jellyfin.${SECRET_PUBLIC_DOMAIN1}"
    rules:
      - backendRefs:
        - name: jellyfin
          port: *port



persistence:
  config:
    enabled: true
    existingClaim: jellyfin-config
    globalMounts:
      - path: /config
        readOnly: false
      - path: /var/lib/jellyfin/root
        readOnly: false
        subPath: root
  cache:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /cache
        readOnly: false
  media:
    enabled: true
    type: persistentVolumeClaim
    existingClaim:  entertainment-storage-nfs-media
    globalMounts:
      - path: /shared/Media
        readOnly: false

