controllers:
  app:
    enabled: true
    type: deployment
    replicas: 1
    pod:
      hostname: &app kavita
      annotations:
        app.kubernetes.io/name: *app
        app.kubernetes.io/instance: *app
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/kavita
          tag: 0.8.5
          pullPolicy: IfNotPresent
        env:
          PUID: 1000
          PGID: 1000
          TZ: ${TIMEZONE}
        resources:
          requests:
            cpu: 50m
            memory: 300Mi
          limits:
            memory: 1Gi

        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: &port 5000
              initialDelaySeconds: 20
              periodSeconds: 60
              timeoutSeconds: 120
              failureThreshold: 5
          readiness: *probe


defaultPodOptions:
  nodeSelector:
    node-role.kubernetes.io/worker: ""

service:
  web:
    controller: app
    ports:
      http:
        port: *port

route:
  main:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: traefik-private-default
        namespace: network
        sectionName: https-wildcard-secret-private-domain
    hostnames:
      - "kavita.${SECRET_PRIVATE_DOMAIN}"
    rules:
      - backendRefs:
        - name: *app
          port: *port


persistence:
  kavita-config:
    existingClaim: kavita-config
    globalMounts: 
      - path: /config
        readOnly: false
  media:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: entertainment-storage-nfs-media
    globalMounts:
      - path: /shared/Media
        readOnly: false

