controllers:
  app:
    enabled: true
    type: deployment
    replicas: 1
    pod:
      hostname: ${app}
      annotations:
        app.kubernetes.io/name: ${app}
        app.kubernetes.io/instance: ${app}
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/sabnzbd
          tag: 4.4.1
          pullPolicy: IfNotPresent
        env:
          PUID: 1000
          PGID: 1000
          TZ: ${TIMEZONE}
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            memory: 4Gi

        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: ${port}
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probe


defaultPodOptions:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: node-priority
                operator: In
                values:
                - "1"
        - weight: 2
          preference:
            matchExpressions:
              - key: node-priority
                operator: In
                values:
                - "2"

service:
  web:
    controller: app
    ports:
      http:
        port: ${port}

route:
  main:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: traefik-private-default
        namespace: network
        sectionName: https-wildcard-secret-private-domain
    hostnames:
      - ${host}
    rules:
      - backendRefs:
        - name: ${app}
          port: ${port}
        # filters:
        #   - type: ExtensionRef
        #     extensionRef:
        #       group: traefik.io
        #       kind: Middleware
        #       name: authentik


persistence:
  sabnzbd-config:
    existingClaim: sabnzbd-config
    globalMounts:
      - path: /config
        readOnly: false
  media:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: entertainment-storage-nfs-media
    globalMounts:
      - path: /shared/Media
        readOnly: false

