apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_TRAEFIK_PUBLIC_ADDR: ENC[AES256_GCM,data:7MKkFE8MDDVp,iv:gZdU9pgT9oQwaAsPnw0wcLlLXNcZhIBqzWm6AtSVlxQ=,tag:TFiwpfOiuSLaJdUCGUXcJQ==,type:str]
    SECRET_TRAEFIK_PRIVATE_ADDR: ENC[AES256_GCM,data:NrQDA+Zhba0W,iv:XTZSLQ8SpvBssFh8K95m0VC85dy0iPKPKgHBgdJ74yE=,tag:xwOr770AOly4bbKOfz+ICQ==,type:str]
    SECRET_PUBLIC_DOMAIN1: ENC[AES256_GCM,data:nGD6goyxGH5bNRk=,iv:SnFSceF7dvL7zURZMGnUQo/8F5tQ2OeWKrHs6NF9+JQ=,tag:NJD2h+AMcQqaBLxXbAgiyA==,type:str]
    SECRET_PUBLIC_DOMAIN2: ENC[AES256_GCM,data:V/AEwWYGQXEF,iv:1jQSaCeS3zN8CmW55oFpoPrfhzmORRx0WWYEeUi4nRE=,tag:AgsTcKJNkPGFRCayDlrUXA==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:jY4nmomuIJF9/e/Q8RQinw==,iv:2ITrHk/ITuFR6qzZuJ19afEmIV6UW/V+h2KiYFc7MFg=,tag:uCqlSARaMjSFs8L0i747dQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:p0ZpSP/9l1wXRjXg8zWen61+nJoSSmdX6lrJNq8=,iv:r1IDwSmmPdgE1f0Rop7xAHp42viQEEGnBiMVbpFtNsI=,tag:lgZh9WiFQuNjS5DpiM8M+g==,type:str]
    SECRET_CF_TOKEN: ENC[AES256_GCM,data:49Ljh4YM/wcq1lvRz7TOEEPIJk5iqIq6s+qlT4gn/9+vn75GhwdLlA==,iv:D9G4vWu4Ew/afo11YikAJy7ox8ozotqVrEdRwUupO6I=,tag:9YhqC/ae/vj4BGJITqU2Kw==,type:str]
    SECRET_NFS_ADDR: ENC[AES256_GCM,data:PgGHTaMjeaw=,iv:u1+vgy8TQ1d1G82PO0fNxGbliWQDa7kU5qywvFxZ7es=,tag:hz0p3+oa1nhqX94jRA7zCA==,type:str]
    SECRET_NFS_MEDIA_PATH: ENC[AES256_GCM,data:+V1odEyxFQ==,iv:bDXbp06RGv7KOilxB2vVaHK5/oN1pOnzt0+QKt3QI2A=,tag:4AqudYoufXmbADLn3q3Sag==,type:str]
    SECRET_PMX_ADDR: ENC[AES256_GCM,data:tFb7fQizfBojGA==,iv:cQ1vA+uCJQdmkJqq9W/zKtvlZHgP3XC9SNE2yHXg/2o=,tag:AhNIrz1VTkNANUYh+KmiZQ==,type:str]
    SECRET_PMX1_ADDR: ENC[AES256_GCM,data:oM+89DaMukAGtQ==,iv:5J7k+yCcFNUB3ZKaxiNyb0F5mHATJ4WIjhM4qfM5DbQ=,tag:GUkBL/IijVDGBgAZdMn80w==,type:str]
    SECRET_PMX2_ADDR: ENC[AES256_GCM,data:dQ5INUxAtFHJYg==,iv:TaEIHE3vpYk4jXwAsMyPvtbqsuZcsRpOAS82v36BM9A=,tag:iktM29zJm9Dgpquav8iC2w==,type:str]
    SECRET_PMX_PORT: ENC[AES256_GCM,data:NFG80A==,iv:p//UiQuFlaUJZl3WffrB/7q0jj0tPAAgHPFzRkpm7Hg=,tag:yRI8kgn1BODLF3le/RsiNg==,type:int]
    SECRET_ADGUARD_ADDR: ENC[AES256_GCM,data:Odcd9FSgVy3stg==,iv:a3k0omnbSbleDYfPrh1W/c8P5wGcRN0gm0Je2ZafeAk=,tag:fsePwmNHHyrECqSR1MnWwA==,type:str]
    SECRET_ADGUARD_PORT: ENC[AES256_GCM,data:HK4=,iv:rI/Z4x7uU29cciTJIlwJqus8Or0TQ8/7YtqOJokpCSE=,tag:XjNLxHkinZX4fvBeP9OajQ==,type:int]
    SECRET_HASS_ADDR: ENC[AES256_GCM,data:5JJD8zQ3a0k=,iv:EkbcPN/06ZisUe+PTBfuVcT8EeuPnjJS4/TEi6shhEE=,tag:88iUg5cGws5mLuOVWazuVA==,type:str]
    SECRET_HASS_PORT: ENC[AES256_GCM,data:r6Cecg==,iv:sk9uI/GQ820W5/aBiqexTwNAuRaCR4um1X4C9UP9uFc=,tag:Ut9TVfLAaziuppTCa1KqLw==,type:int]
    SECRET_NC_ADDR: ENC[AES256_GCM,data:0bioc1L4SFDd,iv:8emb+HnOCjzzO9tbcdOiIPTkx9AnEUqfepKRHbouOuc=,tag:CsbQ9Rxx9J/kHBqbLiXJ+Q==,type:str]
    SECRET_NC_PORT: ENC[AES256_GCM,data:5pKOYZY=,iv:0ZD0HHQTdcga3mMEVZfsRM2S002Zmpi2iPlQB/r0Z30=,tag:KpI6CfVX10bNFfE8eKnAyg==,type:int]
    SECRET_NR_ADDR: ENC[AES256_GCM,data:wm+UCcYUYrbm,iv:yWgiwnAgg/enTeohGrHZeoYc+bboCUrVHLcwpbU1A9Q=,tag:KGbYf0v5S6taumawyfpp7w==,type:str]
    SECRET_NR_PORT: ENC[AES256_GCM,data:VkgI+A==,iv:o3Z1inMm9WZVfQuD9nQkLli1QVQdWhUUD5wr3HF9q3Y=,tag:q+Mi2VX2QDG6KdQkaxO/ig==,type:int]
    SECRET_OMV_ADDR: ENC[AES256_GCM,data:omSri5FaHAU=,iv:lPfNEYc7/eHWBQHSVniILFE8gReDBDFJKHss3y57bEI=,tag:ZHNn1Fm7/FiBgGuVNU+GXA==,type:str]
    SECRET_OMV_PORT: ENC[AES256_GCM,data:JOY=,iv:CVCxwBDwzJSlgBU3eTh/S6xELp5Rd7XMQU53UMgUJWU=,tag:ZPCFidS+ua7e/Bk91Pxlrw==,type:int]
    SECRET_OPN_ADDR: ENC[AES256_GCM,data:zJnV9JzDnvI=,iv:75H1J7gu4Lk5AJlAaHUakJ8Ym6/7EdP1taBwKrddGXo=,tag:sHqj8yxIFO3rTnXDZHHPeA==,type:str]
    SECRET_OPN_PORT: ENC[AES256_GCM,data:Xxg=,iv:a0nUgYtG0sbmh2V47Mwd06/H9DpOIf5Rp3hJi0M15wo=,tag:tHBNM6mG+68v3CjW69vsBg==,type:int]
    SECRET_PTERO_ADDR: ENC[AES256_GCM,data:hd4Tq9XBwV8Z,iv:o95Frgx3AVT38U870DtLElZyl894YEJAgbEM83fdOBU=,tag:I+HsSc6UQwpViF0QnhsMzw==,type:str]
    SECRET_PTERO_PORT: ENC[AES256_GCM,data:X+dv,iv:7bPh/Id+dMq7pCaQfi2JWXEVFrjOWiQS8AgtE4hYnLg=,tag:DC0HotSReB77MK+yR4I2Qg==,type:int]
    SECRET_PTERO_NODE1_ADDR: ENC[AES256_GCM,data:Vxr0lkIDaeRY,iv:hdjUp56iW93QRlLRvrhT5GFL/oYiu9jcHlSfLhXtiek=,tag:zNSGiOehnAMQZa0jsp8bHQ==,type:str]
    SECRET_PTERO_NODE1_PORT: ENC[AES256_GCM,data:MVMrsw==,iv:gpzVxWSebJ/T/qYyb00tXlYjgapW2xore1w7mAvkTb4=,tag:LZicMkvCryBjzwmvdFb8Vw==,type:int]
    SECRET_VW_ADDR: ENC[AES256_GCM,data:FkFwJWPAvnE=,iv:oM4H0iebZP3QlQ/DQq+lvE4NsRQjPHw7/ePXRMtY56g=,tag:NbiyvszgYOrn+z+UJf880Q==,type:str]
    SECRET_VW_PORT: ENC[AES256_GCM,data:oE11jg==,iv:AIJ/a8hDxaUObzvSbhwMa2gwoFcp7YeKigrdM5RrUJ0=,tag:q+S4TPNSrjb5A3BE3gOjZQ==,type:int]
    SECRET_KITCHENOWL_JWT_SECRET_KEY: ENC[AES256_GCM,data:dNO5d+8bhzMLSIEhnXJGlbYoaCn5tKBB4rdwxAXxNJH8fCAs0jYE3L2s+IiYrYLwMdFOxYYNRGnrtWI8lAcZvA==,iv:qtZdWzo2FC2swkki37ybH8mU+wEchmYxrtEU2C8po0k=,tag:R469lXKVKWC0P1lzK+75Pg==,type:str]
    SECRET_TDARR_IP: ENC[AES256_GCM,data:lAfoqdcIGgde,iv:olWhYk6eENrk1dNB7w2Auj1is7rzwinCrb1a+2NydkY=,tag:PomqrQ0bnPuGnFVR+c93cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uem8zcylkmwcsgxulla00cn0yrgvhusua0mg5emuav4ja30cvvq3sdu0r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbmhzbEJabk5SL211NlBm
            OFd6RmJHK3pvVU0zUTdwMTlORHpuYlI2QVgwCmhTQXhtRDlxcngrclFtM2liVVg2
            ektkcTMyWU5MU3RrMk5WQk1HcWtGSEUKLS0tIDAxU21lMS8wRnJKNlcyRE8xM1Nh
            MW1NUGYxVlJISEJkMDByODFUbHlZZmcKb3f8bhgsHXyE4kaSuZEBvUbaGtAz6SQy
            bE0FUEWymYBD50yhBjgnbZuOrVqBp+J1aXOkE25PkKwtZPQx0NGs/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-27T12:23:20Z"
    mac: ENC[AES256_GCM,data:4KuJu8Vm0uqxy9QyiKFzp164BkwJyt46/ucwtbOjGA1l25mFR/aMPdlAMV8+CjInCXwWf3VdtYWbKs2tGi1P2WDthzOr+ahWLl+o/37JIHVkWAeoePJrlCCAb+BZ78gifT30L+GnJzSNI7K0/U74bz22faEQNt7hVExh//dYuO4=,iv:tWPyCFAAi3AOV2iMwlfLmtNm6GpvMFPezlhbT9KCjRI=,tag:nyKPETnAaQ1T5KmaV2QyOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
