---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name private-repo-auth
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: *name

  data:
    - secretKey: username
      remoteRef:
        key: GITHUB_AUTH_USERNAME
    - secretKey: password
      remoteRef:
        key: GITHUB_AUTH_TOKEN