---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name private-repo-auth
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: *name

  dataFrom:
    - find:
        name: 
          regexp: &prefix "GITHUB_SELF_(.*)"
      rewrite:
        - regexp:
            source: *prefix
            target: "$1"
          transform:
            template: '{{ .value | lower | replace "token" "password" }}'