---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 16.4.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 16.2.0-debian-12-r8
    auth:
      username: entertainment
      password: password
    primary:
      persistence:
        enabled: true
        existingClaim: entertainment-postgresql
