apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infisical-credentials
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infisical-credentials
      # Details to pull secrets from
      secretsScope:
        projectSlug: athena-ops-t-kuq
        environmentSlug: prod # "dev", "staging", "prod", etc..
        # optional
        secretsPath: / # Root is "/"
        # optional
        recursive: true # Default is false
      # optional
      hostAPI: http://infisical-infisical-standalone-infisical:8080/