apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name ${KS_NAME}-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: *name
  resources:
    requests:
      storage: 1Gi
