apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reflector
spec:
  chart:
    spec:
      chart: reflector
      version: 7.1.x
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: flux-system
  releaseName: reflector
  targetNamespace: kube-system
  interval: 1h # this is for drifting of the helm created resources
  values:
    selector:
      node-role.kubernetes.io/control-plane: ""
