defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 2000
    runAsGroup: 2000
    fsGroup: 2000
    fsGroupChangePolicy: OnRootMismatch
controllers:
  app:
    strategy: RollingUpdate
    enabled: true
    type: deployment
    replicas: 1
    pod:
      hostname: &app atuin
      annotations:
        app.kubernetes.io/name: *app
        app.kubernetes.io/instance: *app
    containers:
      app:
        image:
          repository: ghcr.io/szinn/atuin
          tag: v18.6.1-sqlite-5
        env:
          # RUST_LOG: "info"
          ATUIN_HOST: "0.0.0.0"
          ATUIN_PORT: &port 8080
          ATUIN_OPEN_REGISTRATION: "true"
          ATUIN_DB_URI: "sqlite:///config/atuin.db"
          TZ: Europe/Lisbon
        command: ["atuin", "server", "start"]
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 512Mi

        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *port
              initialDelaySeconds: 20
              periodSeconds: 30
              timeoutSeconds: 20
              failureThreshold: 5
          readiness: *probe
service:
  app:
    controller: app
    ports:
      http:
        port: *port
route:
  main:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: traefik-public-default
        namespace: network
        sectionName: https-atuin
    hostnames:
      - "atuin.${SECRET_PUBLIC_DOMAIN1}"
    rules:
      - backendRefs:
        - name: *app
          port: *port

persistence:
  config:
    existingClaim: atuin-data
