apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name jellystat
  namespace: flux-system
spec:
  targetNamespace: entertainment
  interval: 10m0s
  retryInterval: 1m
  path: ./kubernetes/apps/entertainment/jellystat/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: crunchy-postgres-operator-cluster
    - name: infisical
  postBuild:
    substitute:
      app: *name
      port: "3000"
      host: "jellystat.${SECRET_PRIVATE_DOMAIN}"
