---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      homepage:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v0.10.7@sha256:b261c981a866a0e287205394bf365bd8cdb9152469a85ec569d7bfcd7812cf14
            env:
              TZ: Europe/Lisbon
            resources:
              requests:
                cpu: 15m
                memory: 200M
              limits:
                memory: 512Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000
    ingress:
      homepage:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        className: traefik-private
        hosts:
          - host: &homepage-path ${SECRET_PRIVATE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: ${SECRET_PRIVATE_DOMAIN//./-}-tls
            hosts:
              - *homepage-path
      homepage-public:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: ${SECRET_PUBLIC_DOMAIN1}
        className: traefik-public
        hosts:
          - host: &homepage-public-path newtab.${SECRET_PUBLIC_DOMAIN1}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: newtab-${SECRET_PUBLIC_DOMAIN1//./-}-tls
            hosts:
              - *homepage-public-path
    persistence:
      config:
        enabled: true
        type: nfs
        server: ${SECRET_NFS_ADDR}
        path: /Documents
        globalMounts:
          - path: /app/config
            subPath: Homepage
    serviceAccount:
      create: true
      name: *app
