service:
  web:
    controller: app
    ports:
      http:
        port: &port 5055

route:
  main:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: traefik-private-default
        namespace: network
        sectionName: https-wildcard-secret-private-domain
    hostnames:
      - "jellyseerr.${SECRET_PRIVATE_DOMAIN}"
    rules:
      - backendRefs:
        - name: jellyseerr
          port: *port


controllers:
  app:
    enabled: true
    type: deployment
    replicas: 1
    pod:
      hostname: &app jellyseerr
      annotations:
        app.kubernetes.io/name: *app
        app.kubernetes.io/instance: *app
    containers:
      app:
        image:
          repository: fallenbagel/jellyseerr
          tag: 2.5.1
          pullPolicy: IfNotPresent
        env:
          PUID: 1000
          PGID: 1000
          TZ: ${TIMEZONE}
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            memory: 1Gi

        # probes:
        #   liveness: &probe
        #     enabled: true
        #     custom: true
        #     spec:
        #       httpGet:
        #         path: /api/v1/status
        #         port: &port 5055
        #       initialDelaySeconds: 0
        #       periodSeconds: 10
        #       timeoutSeconds: 1
        #       failureThreshold: 3
        #   readiness: *probe


defaultPodOptions:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: node-priority
                operator: In
                values:
                - "1"
        - weight: 2
          preference:
            matchExpressions:
              - key: node-priority
                operator: In
                values:
                - "2"

persistence:
  jellyseerr-config:
    existingClaim: jellyseerr-config
    globalMounts:
      - path: /app/config
        readOnly: false
  media:
    enabled: true
    type: persistentVolumeClaim
    existingClaim:  entertainment-storage-nfs-media
    globalMounts:
      - path: /shared/Media
        readOnly: false

