apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  targetNamespace: databases
  interval: 10m0s
  retryInterval: 1m
  path: ./kubernetes/apps/databases/dragonfly/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-cluster
  namespace: flux-system
spec:
  targetNamespace: databases
  interval: 10m0s
  retryInterval: 1m
  path: ./kubernetes/apps/databases/dragonfly/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
