controllers:
  app:
    enabled: true
    type: deployment
    replicas: 1
    pod:
      hostname: &name calibre
      annotations:
        app.kubernetes.io/name: *name
        app.kubernetes.io/instance: *name
    containers:
      app:
        image:
          repository: ghcr.io/linuxserver/calibre
          tag: v7.26.0-ls326
          pullPolicy: IfNotPresent
        env:
          PUID: 1000
          PGID: 1000
          TZ: ${TIMEZONE}
        resources:
          requests:
            cpu: 15m
            memory: 100Mi
          limits:
            memory: 2Gi

        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: &port 8080
              initialDelaySeconds: 20
              periodSeconds: 30
              timeoutSeconds: 20
              failureThreshold: 5
          readiness: *probe


defaultPodOptions:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: node-priority
                operator: In
                values: 
                - "1"
        - weight: 2
          preference:
            matchExpressions:
              - key: node-priority
                operator: In
                values: 
                - "2"

service:
  app:
    controller: app
    ports:
      http:
        primary: true
        port: &http-port 8080
      webserver:
        enabled: true
        port: &ws-port 8081

route:
  gui:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: traefik-private-default
        namespace: network
        sectionName: https-wildcard-secret-private-domain
    hostnames:
      - "calibre.${SECRET_PRIVATE_DOMAIN}"
    rules:
      - backendRefs:
        - name: calibre
          port: *http-port
  webserver:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: traefik-private-default
        namespace: network
        sectionName: https-wildcard-secret-private-domain
    hostnames:
      - "calibre-web.${SECRET_PRIVATE_DOMAIN}"
    rules:
      - backendRefs:
        - name: calibre
          port: *ws-port

persistence:
  config:
    enabled: true
    existingClaim: calibre
    globalMounts:
      - path: /config
        readOnly: false
  media:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: entertainment-storage-nfs-media
    globalMounts:
      - path: /shared/Media
        readOnly: false

