controllers:
  app:
    enabled: true
    type: deployment
    replicas: 1
    pod:
      hostname: ${app}
      annotations:
        app.kubernetes.io/name: ${app}
        app.kubernetes.io/instance: ${app}
    containers:
      app:
        image:
          repository: ghcr.io/linuxserver/calibre
          tag: v7.26.0-ls326
          pullPolicy: IfNotPresent
        env:
          PUID: 1000
          PGID: 1000
          TZ: ${TIMEZONE}
        resources:
          requests:
            cpu: 15m
            memory: 100Mi
          limits:
            memory: 2Gi

        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: ${http_port}
              initialDelaySeconds: 20
              periodSeconds: 30
              timeoutSeconds: 20
              failureThreshold: 5
          readiness: *probe


defaultPodOptions:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: node-priority
                operator: In
                values:
                - "1"
        - weight: 2
          preference:
            matchExpressions:
              - key: node-priority
                operator: In
                values:
                - "2"

service:
  app:
    controller: app
    ports:
      http:
        primary: true
        port: ${http_port}
      webserver:
        enabled: true
        port: ${ws_port}

route:
  gui:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: traefik-private-default
        namespace: network
        sectionName: https-wildcard-secret-private-domain
    hostnames:
      - "${http_host}"
    rules:
      - backendRefs:
        - name: calibre
          port: ${http_port}
        # filters:
        #   - type: ExtensionRef
        #     extensionRef:
        #       group: traefik.io
        #       kind: Middleware
        #       name: authentik
  webserver:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: traefik-private-default
        namespace: network
        sectionName: https-wildcard-secret-private-domain
    hostnames:
      - "${ws_host}"
    rules:
      - backendRefs:
        - name: calibre
          port: ${ws_port}
        # filters:
        #   - type: ExtensionRef
        #     extensionRef:
        #       group: traefik.io
        #       kind: Middleware
        #       name: authentik

persistence:
  config:
    enabled: true
    existingClaim: calibre
  media:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: entertainment-storage-nfs-media
    globalMounts:
      - path: /shared/Media
        readOnly: false

