---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name jellystat-secrets
spec:
  refreshInterval: 1m
  target:
    name: *name

  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: JELLYSTAT_AUTH_SECRET
      sourceRef:
        storeRef:
          name: infisical
          kind: ClusterSecretStore

    - secretKey: POSTGRES_IP
      remoteRef:
        key: postgres-pguser-entertainment
        property: host
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore

    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres-pguser-entertainment
        property: user
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore
    
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-pguser-entertainment
        property: password
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore