controllers:
  app:
    enabled: true
    type: deployment
    replicas: 1
    containers:
      app:
        image:
          repository: cyfershepard/jellystat
          tag: 1.1.2
          pullPolicy: IfNotPresent
        env:
          TZ: ${TIMEZONE}
          POSTGRES_PORT: 5432
          POSTGRES_DB: jellystat
        envFrom:
          - secretRef:
              name: jellystat-secrets
        resources:
          requests:
            cpu: 15m
            memory: 300Mi
          limits:
            memory: 1Gi

        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: &port 3000
              initialDelaySeconds: 20
              periodSeconds: 30
              timeoutSeconds: 20
              failureThreshold: 5
          readiness: *probe


defaultPodOptions:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: node-priority
                operator: Gt
                value: 0
        - weight: 2
          preference:
            matchExpressions:
              - key: node-priority
                operator: Gt
                value: 1

service:
  web:
    controller: app
    ports:
      http:
        port: *port

route:
  main:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: traefik-private-default
        namespace: network
        sectionName: https-wildcard-secret-private-domain
    hostnames:
      - "jellystat.${SECRET_PRIVATE_DOMAIN}"
    rules:
      - backendRefs:
        - name: jellystat
          port: *port


persistence:
  backup-data:
    existingClaim: jellystat-backup-data
    globalMounts: 
      - path: /app/backend/backup-data
        readOnly: false

  media:
    enabled: true
    type: persistentVolumeClaim
    existingClaim:  entertainment-storage-nfs-media
    globalMounts:
      - path: /shared/Media
        readOnly: false

