---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-public-default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  gatewayClassName: traefik-public
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All

    - name: https-hass
      protocol: HTTPS
      hostname: "hass.${SECRET_PUBLIC_DOMAIN1}"
      port: 443
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: hass-tls