---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name linkwarden-secrets
spec:
  refreshInterval: 1m
  target:
    name: *name

  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: LINKWARDEN_AUTH_SECRET
      sourceRef:
        storeRef:
          name: infisical
          kind: ClusterSecretStore

    - secretKey: DATABASE_URL
      remoteRef:
        key: postgres-pguser-linkwarden
        property: uri
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore