---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name linkwarden-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: *name

  dataFrom:
    - find:
        name:
          regexp: &prefix "LINKWARDEN_(.*)"
      rewrite:
        - regexp:
            source: *prefix
            target: "$1"

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: postgres-pguser-linkwarden
        property: uri
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore
