---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name romm-secrets
spec:
  refreshInterval: 1m
  target:
    name: *name

  data:
    - secretKey: ROMM_AUTH_SECRET_KEY
      remoteRef:
        key: ROMM_AUTH_SECRET_KEY
      sourceRef:
        storeRef:
          name: infisical
          kind: ClusterSecretStore

    - secretKey: IGDB_CLIENT_ID
      remoteRef:
        key: IGDB_CLIENT_ID
      sourceRef:
        storeRef:
          name: infisical
          kind: ClusterSecretStore

    - secretKey: IGDB_CLIENT_SECRET
      remoteRef:
        key: IGDB_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: infisical
          kind: ClusterSecretStore

    - secretKey: MOBYGAMES_API_KEY
      remoteRef:
        key: MOBYGAMES_API_KEY
      sourceRef:
        storeRef:
          name: infisical
          kind: ClusterSecretStore

    - secretKey: STEAMGRIDDB_API_KEY
      remoteRef:
        key: STEAMGRIDDB_API_KEY
      sourceRef:
        storeRef:
          name: infisical
          kind: ClusterSecretStore

    - secretKey: SCREENSCRAPER_USER
      remoteRef:
        key: SCREENSCRAPER_USER
      sourceRef:
        storeRef:
          name: infisical
          kind: ClusterSecretStore

    - secretKey: SCREENSCRAPER_PASSWORD
      remoteRef:
        key: SCREENSCRAPER_PASSWORD
      sourceRef:
        storeRef:
          name: infisical
          kind: ClusterSecretStore

    - secretKey: DB_HOST
      remoteRef:
        key: postgres-pguser-romm
        property: host
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore

    - secretKey: DB_PORT
      remoteRef:
        key: postgres-pguser-romm
        property: port
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore

    - secretKey: DB_NAME
      remoteRef:
        key: postgres-pguser-romm
        property: dbname
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore

    - secretKey: DB_USER
      remoteRef:
        key: postgres-pguser-romm
        property: user
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore
    
    - secretKey: DB_PASSWD
      remoteRef:
        key: postgres-pguser-romm
        property: password
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore