---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name romm-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      mergePolicy: Merge
      templateFrom:
        - target: Data
          literal: |
            {{- $myvar := .DB_PORT | fromJson -}}
            DB_PORT: {{ $myvar.port }}
            DB_NAME: {{ $myvar.dbname }}
            DB_USER: {{ $myvar.user }}
            DB_PASSWD: {{ $myvar.password }}
            DB_HOST: {{ $myvar.host }}


  dataFrom:
    - find:
        name:
          regexp: &prefix "ROMM_(.*)"
      rewrite:
        - regexp:
            source: *prefix
            target: "$1"
    - find:
        path: IGDB_
    - find:
        path: SCREENSCRAPER_
    - find:
        path: MOBYGAMES_
    - find:
        path: STEAMGRIDDB_

  data:
    - secretKey: DB_PORT
      remoteRef:
        key: postgres-pguser-romm
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore
