---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name romm-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      mergePolicy: Merge
      templateFrom:
        - target: Data
          literal: |
            {{- $dbCreds := .DB_CREDS | fromJson -}}
            DB_PORT: {{ $dbCreds.port }}
            DB_NAME: {{ $dbCreds.dbname }}
            DB_USER: {{ $dbCreds.user }}
            DB_PASSWD: {{ $dbCreds.password }}
            DB_HOST: {{ $dbCreds.host }}
            HASHEOUS_API_ENABLED: true
            HLTB_API_ENABLED: true
  dataFrom:
    - find:
        path: /ROMM
    - find:
        path: /IGDB
      rewrite:
        - transform:
            template: "IGDB_{{ .value }}"
    - find:
        path: /SCREENSCRAPER
      rewrite:
        - transform:
            template: "SCREENSCRAPER_{{ .value }}"

  data:
    - secretKey: STEAMGRIDDB_API_KEY
      remoteRef:
        key: STEAMGRIDDB_API_KEY
    - secretKey: RETROACHIEVEMENTS_API_KEY
      remoteRef:
        key: RETROACHIEVEMENTS_API_KEY
    - secretKey: DB_CREDS
      remoteRef:
        key: postgres-pguser-romm
      sourceRef:
        storeRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore
